# Generated by Django 3.0.7 on 2020-09-30 23:35

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='the_image',
            field=models.ImageField(blank=True, null=True, upload_to=places.models.place_image_upload_to),
        ),
    ]
