name: Setup Python Environment
description: Checkout, configure Python, install uv, and sync the project

runs:
  using: composite
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version-file: "pyproject.toml"
    - name: Install uv
      uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7
      with:
        enable-cache: true
    - name: Install the project
      run: uv sync --locked --all-extras --dev
      shell: bash
