# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newsarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
