language: python
sudo: required
dist: xenial
python: "3.7"

notifications:
  email: false

branches:
  only:
  - master
  - develop

install:
  - pip install pipenv
  - pipenv --python 3
  - pipenv install --dev

script: 
  - pipenv run pytest
