language: python
sudo: required
dist: xenial
python: "3.7"

notifications:
  email: false

branches:
  only:
    - master
    - develop

install:
  - pip install poetry
  - poetry install

script:
  - poetry run pytest
