# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=70)),
                ('slug', models.SlugField()),
                ('published_datetime', models.DateTimeField()),
                ('published', models.BooleanField()),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
