# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='galleryimage',
            unique_together=set([('gallery', 'slug')]),
        ),
    ]
