# Generated by Django 3.0.7 on 2020-09-30 23:35

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20181103_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='the_image',
            field=models.ImageField(upload_to=gallery.models.gallery_image_upload_to),
        ),
    ]
