# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0005_auto_20170707_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField()),
                ('slug', models.SlugField()),
                ('vital_stats', models.TextField(blank=True)),
                ('backstory', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('the_image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.GalleryImage')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='character',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Team'),
        ),
        migrations.AddField(
            model_name='character',
            name='the_image',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.GalleryImage'),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together=set([('team', 'slug')]),
        ),
    ]
