# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 00:07
from __future__ import unicode_literals

import characters.models
from django.db import migrations, models
import dotmanca.storage


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_remove_character_the_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='the_image',
            field=models.ImageField(blank=True, null=True, storage=dotmanca.storage.OverwriteStorage(), upload_to=characters.models.character_image_upload_to),
        ),
    ]
