# Generated by Django 4.1 on 2022-08-19 17:56

import characters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_character_the_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='the_image',
            field=models.ImageField(blank=True, null=True, upload_to=characters.models.character_image_upload_to),
        ),
    ]
