# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='published',
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(unique_for_date='published_datetime'),
        ),
    ]
