# Generated by Django 2.0 on 2018-01-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170616_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='published_datetime',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(unique_for_date='published_date'),
        ),
    ]
