# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install poetry
            poetry install

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: run tests
          command: |
            poetry run pytest

  # deploy:
  #   docker:
  #     - image: circleci/python:3.7.4
  #   steps:
  #     - run:
  #         name: deploy over ssh
  #         command: |
  #           ssh $SSH_USER@$SSH_HOST "cd dotmanca && git pull && poetry install --no-dev && poetry run python manage.py migrate && poetry run python manage.py collectstatic && sudo /bin/systemctl restart gunicorn"

workflows:
  version: 2

  # The build-and-test we will run EVERYTIME a piece of code changes
  build-and-test-workflow:
    jobs:
      - build-and-test
  # build-test-deploy-workflow:
  #   jobs:
  #     - build-and-test
  #     - deploy:
  #       requires: build-and-test
  #       filters:
  #         branches:
  #           only: master
