# Generated by Django 2.1.2 on 2018-11-03 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_auto_20180314_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery'),
        ),
    ]
