# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20170707_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='the_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.GalleryImage'),
        ),
    ]
