# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20170707_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='the_image',
        ),
    ]
