# Generated by Django 2.0.2 on 2018-03-08 02:32

import comics.models
from django.db import migrations, models
import django.db.models.deletion
import dotmanca.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField()),
                ('the_image', models.ImageField(storage=dotmanca.storage.OverwriteStorage(), upload_to=comics.models.arc_image_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField()),
                ('the_image', models.ImageField(storage=dotmanca.storage.OverwriteStorage(), upload_to=comics.models.arc_image_upload_to)),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Arc')),
            ],
        ),
    ]
