# Generated by Django 2.0.3 on 2018-03-15 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20170714_1311'),
        ('comics', '0002_auto_20180311_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery'),
        ),
    ]
