# Generated by Django 2.0.3 on 2018-03-15 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_issue_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery'),
        ),
    ]
