# Generated by Django 3.0.2 on 2020-02-09 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_auto_20181103_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='arc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='comics.Arc'),
        ),
    ]
