# Generated by Django 4.1 on 2022-08-19 17:56

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='the_image',
            field=models.ImageField(blank=True, null=True, upload_to=places.models.place_image_upload_to),
        ),
    ]
