name: "Run a poetry command"
description: "Builds and runs a poetry/tox environment"
inputs:
   python-version:
     required: true
     description: "The Python version to use"
   command:
     required: true
     description: "The command to run"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install poetry
      run: pip install poetry
      shell: bash
    - name: Run command
      run: ${{ inputs.command }}
      shell: bash